### ISSUE TITLE
Access to this repo for future bloom releases of fmilibrary_vendor

### ISSUE THREAD

**Issue by ralph-lange** [ros2-gbp/fmilibrary_vendor-release#1]
Hi @nuclearsandwich, could you please grant me access to this repo for future bloom releases of fmilibrary_vendor just as you did yesterday for https://github.com/ros2-gbp/fmi_adapter_ros2-release/?

**Comment by ralph-lange** [comment]
Friendly reminder, @nuclearsandwich

**Comment by clalancette** [comment]
I've gone ahead and given you admin access @ralph-lange .  Closing this out.
